from app.routers.summarization import _translate
try:
    source_en = "This is a summary generated by the model."
    res = _translate(source_en, "te")
    print(f"Translation Output: {res}")
except Exception as e:
    print(f"Error: {e}")
